### ISSUE TITLE
Weird class names?

### ISSUE THREAD

**Issue by ramon-plusb** [huihuimoe/one-page-scroll#1]
Hey. Thanks for your implementation! It's the only onepager plugin that worked for me. 
But I got a strange problem.. the sections that are rendered as full pages have 🛋🍌⛳️🍌 as class name. We need to fix some css issues and would like to access the sections via class name but 🛋🍌⛳️🍌 is just ridiculous..
Is there a reason why you chose emoticons for class name?

**Comment by huihuimoe** [comment]
Hi, it is just a random string generated during building. You can modify [this line](/huihuimoe/one-page-scroll/blob/bf85ac5b8786ca86983e514ce36bb701b9a18e9b/webpack.config.js#L59) and build your own version to change className.
If you have a better idea, discuss welcome

**Comment by ramon-plusb** [comment]
Thanks for your fast response! I would recommend using something like "ops-page" or "one-page-scroll--page" as classname. 
Probably I'll use a workaround and access via wrapper-class rather than building my own version but thanks for your input.

**Comment by huihuimoe** [comment]
I will consider it in next version, thx
